const express = require('express');
const router = express.Router();
const { protect, optionalAuth } = require('../middleware/auth');
const { getRooms, getArchivedRooms, createRoom, getRoom, closeRoom, reactRoom, searchRooms, getMyRooms, getJoinedRooms, deleteRoom, pinRoom, unpinRoom, leaveRoom, getPinnedMoments, getUserMessages, getSubjects, checkLocation, getRadar, recordVisit, getVault, getNearby } = require('../controllers/hachiController');
const flashPoll = require('../controllers/flashPollController');

router.get('/', optionalAuth, getRooms);
router.get('/radar', optionalAuth, getRadar);
router.get('/nearby', optionalAuth, getNearby);
router.get('/vault', protect, getVault);
router.post('/:id/visit', protect, recordVisit);
router.post('/polls/:pollId/vote', protect, flashPoll.votePoll);
router.delete('/polls/:pollId', protect, flashPoll.deletePoll);
router.get('/search', searchRooms);
router.get('/subjects', getSubjects);
router.get('/moments', getPinnedMoments);
router.get('/archived', getArchivedRooms);
router.get('/my', protect, getMyRooms);
router.get('/joined', protect, getJoinedRooms);
router.get('/user-messages/:username', getUserMessages);
router.post('/', protect, createRoom);
router.get('/:id/check-location', optionalAuth, checkLocation);
router.get('/:id/polls', protect, flashPoll.listPolls);
router.post('/:id/polls', protect, flashPoll.createPoll);
router.get('/:id', optionalAuth, getRoom);
router.post('/:id/react', protect, reactRoom);
router.delete('/:id/delete', protect, deleteRoom);
router.post('/:id/pin', protect, pinRoom);
router.delete('/:id/pin', protect, unpinRoom);
router.post('/:id/leave', protect, leaveRoom);

module.exports = router;
